NotificationSES:
  MySESDomain:
    Type: AWS::SES::DomainIdentity
    Properties:
      Domain: my-domain.com   # I will check how to use custom property to get the domain name

  MySESVerification:
    Type: AWS::SES::Verification
    Properties:
      EmailAddress: paul7jakintayo@gmail.com